version: 0.1

phases:
    install:
         commands:
            - echo installing nodejs...
            - curl -sL https://deb.nodesource.com/setup_12.x | bash -
            - apt-get install -y nodejs
            - echo installing yarn...
            - curl -s5 https://dl.yarnpkg.con/debian/pubkey.gpg | apt-key add -
            - echo "deb https://d1.yarnpkg.con/debian/ stable main” | tee /etc/apt/sources.list.d/yarn.list
            - apt install --no-install-recommends yarn
    pre_build:
         commands:
            - echo installing dependencies...
            - npm install
    build:
         comands:
            - echo building...
            - npm run build

artifacts:
    files:
      -   "**/*"
    discard-paths: no
    base-directory: build
